/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompressRouteImport } from './routes/compress'
import { Route as EditRouteImport } from './routes/edit'
import { Route as ImagesToPdfRouteImport } from './routes/images-to-pdf'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ViewSlugRouteImport } from './routes/view.$slug'
import { Route as AuthenticatedAnalyticsDocIdRouteImport } from './routes/_authenticated/analytics.$docId'
import { Route as AuthenticatedWorkspaceDocIdRouteImport } from './routes/_authenticated/workspace.$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressRoute = CompressRouteImport.update({
  id: '/compress',
  path: '/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesToPdfRoute = ImagesToPdfRouteImport.update({
  id: '/images-to-pdf',
  path: '/images-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ViewSlugRoute = ViewSlugRouteImport.update({
  id: '/view/$slug',
  path: '/view/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsDocIdRoute =
  AuthenticatedAnalyticsDocIdRouteImport.update({
    id: '/analytics/$docId',
    path: '/analytics/$docId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceDocIdRoute =
  AuthenticatedWorkspaceDocIdRouteImport.update({
    id: '/workspace/$docId',
    path: '/workspace/$docId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compress': typeof CompressRoute
  '/edit': typeof EditRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/view/$slug': typeof ViewSlugRoute
  '/analytics/$docId': typeof AuthenticatedAnalyticsDocIdRoute
  '/workspace/$docId': typeof AuthenticatedWorkspaceDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compress': typeof CompressRoute
  '/edit': typeof EditRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/view/$slug': typeof ViewSlugRoute
  '/analytics/$docId': typeof AuthenticatedAnalyticsDocIdRoute
  '/workspace/$docId': typeof AuthenticatedWorkspaceDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/compress': typeof CompressRoute
  '/edit': typeof EditRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/view/$slug': typeof ViewSlugRoute
  '/_authenticated/analytics/$docId': typeof AuthenticatedAnalyticsDocIdRoute
  '/_authenticated/workspace/$docId': typeof AuthenticatedWorkspaceDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compress'
    | '/edit'
    | '/images-to-pdf'
    | '/dashboard'
    | '/view/$slug'
    | '/analytics/$docId'
    | '/workspace/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compress'
    | '/edit'
    | '/images-to-pdf'
    | '/dashboard'
    | '/view/$slug'
    | '/analytics/$docId'
    | '/workspace/$docId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/compress'
    | '/edit'
    | '/images-to-pdf'
    | '/_authenticated/dashboard'
    | '/view/$slug'
    | '/_authenticated/analytics/$docId'
    | '/_authenticated/workspace/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompressRoute: typeof CompressRoute
  EditRoute: typeof EditRoute
  ImagesToPdfRoute: typeof ImagesToPdfRoute
  ViewSlugRoute: typeof ViewSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress': {
      id: '/compress'
      path: '/compress'
      fullPath: '/compress'
      preLoaderRoute: typeof CompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images-to-pdf': {
      id: '/images-to-pdf'
      path: '/images-to-pdf'
      fullPath: '/images-to-pdf'
      preLoaderRoute: typeof ImagesToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/view/$slug': {
      id: '/view/$slug'
      path: '/view/$slug'
      fullPath: '/view/$slug'
      preLoaderRoute: typeof ViewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics/$docId': {
      id: '/_authenticated/analytics/$docId'
      path: '/analytics/$docId'
      fullPath: '/analytics/$docId'
      preLoaderRoute: typeof AuthenticatedAnalyticsDocIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/$docId': {
      id: '/_authenticated/workspace/$docId'
      path: '/workspace/$docId'
      fullPath: '/workspace/$docId'
      preLoaderRoute: typeof AuthenticatedWorkspaceDocIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAnalyticsDocIdRoute: typeof AuthenticatedAnalyticsDocIdRoute
  AuthenticatedWorkspaceDocIdRoute: typeof AuthenticatedWorkspaceDocIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAnalyticsDocIdRoute: AuthenticatedAnalyticsDocIdRoute,
  AuthenticatedWorkspaceDocIdRoute: AuthenticatedWorkspaceDocIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CompressRoute: CompressRoute,
  EditRoute: EditRoute,
  ImagesToPdfRoute: ImagesToPdfRoute,
  ViewSlugRoute: ViewSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
